

       $subject =[
            ['Facial hair', 'facial hair'],
            ['Alcohol consumption','alcohol consumption'],
            ['Ambition','ambition'],
            ['Common sense','common sense'],
            ['Confidence','confidence'],
            ['Driving','driving'],
            ['Enthusiasm','enthusiasm'],
            ['Selfie game', 'Selfie game'],
            ['Friendship','friendship'],
            ['Generosity','generosity'],
            ['Honesty','honesty'],
            ['Humor','humor'],
            ['Judgment','judgment'],
            ['Loyalty','loyalty'],
            ['Maturity','maturity'],
            ['Modesty','modesty'],
            ['Open mindedness','open mindedness'],
            ['Outlook on life ','outlook on life '],
            ['Party etiquette','party etiquette'],
            ['Patience','patience'],
            ['Personal hygiene','personal hygiene'],
            ['Pretentiousness ','pretentiousness '],
            ['Profanity','profanity'],
            ['Reliability','reliability'],
            ['Responsiveness','responsiveness'],
            ['Selfishness','selfishness'],
            ['Love of sports', 'Love of sports'],
            ['Thankfulness','thankfulness'],
            ['Thoughtfulness','thoughtfulness'],
            ['Use of social media','use of social media'],
            ['Work ethic','work ethic'],
            ['Political ideology','political ideology'],
            ['Politics', 'politics'],
            ['Fashion sense', 'fashion sense'],
            ['Oversharing', 'oversharing'],
            ['Love of Lady Gaga','love of Lady Gaga'],
            ['Cooking', 'Cooking'],
            ['Acoustic guitar playing at parties', 'acoustic guitar playing at parties'],
            ['Swag', 'Swag'],
            ['Responsiveness', 'Responsiveness'],
            ['Gift-giving', 'gift-giving'],
            ['Flirtatiousness','flirtatiousness'],
            ['Email etiquette', 'Email etiquette'],
            ['Tipping', 'Tipping'],
            ['Fantasy football skill', 'Fantasy football skill'],
            ['Retweeting', 'Retweeting'],
            ['Follow through', 'Follow through'],
            ['Schtick', 'Schtick'],
            ['Love of dogs', 'Love of dogs'],
            ['Musical preferences', 'Musical preferences'],
            ['Posting of baby photos', 'Posting of baby photos'],
            ['V neck collection', 'V neck collection']
          ]
          
      $verb =[
            ['can be','can be'],
            ['might be','might be'],
            ['is','is'],
            ['is definitely','is definitely'],
            ['used to be','used to be']
          ]



      $adjective =[
          ['good','good'],
          ['crappy', 'crappy'], 
          ['fantastic','fantastic'],
          ['bleak','bleak'],
          ['in need of improvement','in need of improvement'],
          ['one hunna', 'one hunna'],
          ['great','great'],
          ['too much','too much'],
          ['above average','above average'],
          ['below average','below average'],
          ['god awful','god awful'],
          ['wonderful','wonderful'],
          ['non-existent', 'non-existent'],
          ['annoying', 'annoying'],
          ['a problem', 'a problem'],
          ['unbearable', 'unbearable'],
          ['controversial', 'controversial'],
          ['zilch', 'zilch'],
          ['off the charts', 'off the charts'],
          ['backwards', 'backwards'],
          ['much improved','much improved'],
          ['bad','bad'],
          ['grimy', 'grimy'], 
          ['juvenile', 'juvenile'], 
          ['ummmm', 'ummmm'], 
          ['emo', 'emo'],
          ['proper', 'proper'],
          ['atrocious', 'atrocious'],
          ['inappropriate', 'inappropriate'], 
          ['obtuse', 'obtuse'],
          ['cute', 'cute'],
          ['tired', 'tired'],
          ['over the top', 'over the top'],
          ['comical', 'comical'],
          ['hypocritical', 'hypocritical'], 
          ['aggravating', 'aggravating'], 
          ['surprisingly good', 'surprisingly good'],
          ['subpar', 'subpar'],
          ['adequate', 'adequate'],
          ['dire', 'dire'],
          ['ambitious', 'ambitious'],
          ['getting better', 'getting better'], 
          ['average', 'average'], 
          ['magnificent', 'magnificent'],
          ['absurd', 'absurd'],
          ['exquisite', 'exquisite'],
          ['depressing', 'depressing'],
          ['as good it gets', 'as good it gets']
          ]